In [2]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [6]:
arr_10_i = np.arange(1, 11, dtype=int)
print(f"arr_10_i:\n {arr_10_i}")

arr_10_i:
 [ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [8]:
m_3x3_i = np.zeros((3, 3), dtype=int)
print(f"arr_3x3_i:\n {m_3x3_i}")

arr_3x3_i:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими 
числами в діапазоні від 1 до 10 та виведіть його значення.

In [9]:
arr_5x5_i = np.random.randint(1, 11, size=(5, 5))
print(f"arr_5x5_i:\n {arr_5x5_i}")

arr_5x5_i:
 [[ 7  4  8  7  4]
 [ 1  5  2  8  7]
 [ 6  2  4  4  4]
 [ 3  2  6  8  2]
 [ 4  7  7 10 10]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [3]:
arr_4x4_f = np.random.rand(4, 4)
print(f"arr_4x4_f:\n {arr_4x4_f}")

arr_4x4_f:
 [[0.03156796 0.02055796 0.09489186 0.05523245]
 [0.49223043 0.34258486 0.75943218 0.17300675]
 [0.79655207 0.1979159  0.94573955 0.63877082]
 [0.03705426 0.30554792 0.15271299 0.49823452]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [4]:
arr1_5_i = np.random.randint(1, 11, size=5)
arr2_5_i = np.random.randint(1, 11, size=5)
print(f"arr1_5_i:\n {arr1_5_i}")
print(f"arr2_5_i:\n {arr2_5_i}")
print(f"arr1_5_i + arr2_5_i:\n {arr1_5_i + arr2_5_i}")
print(f"arr1_5_i - arr2_5_i:\n {arr1_5_i - arr2_5_i}")
print(f"arr1_5_i * arr2_5_i:\n {arr1_5_i * arr2_5_i}")

arr1_5_i:
 [2 2 6 3 5]
arr2_5_i:
 [9 4 8 2 3]
arr1_5_i + arr2_5_i:
 [11  6 14  5  8]
arr1_5_i - arr2_5_i:
 [-7 -2 -2  1  2]
arr1_5_i * arr2_5_i:
 [18  8 48  6 15]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [5]:
v1_7_i = np.random.randint(1, 11, size=7)
v2_7_i = np.random.randint(1, 11, size=7)
print(f"v1_7_i:\n {v1_7_i}")
print(f"v2_7_i:\n {v2_7_i}")
print(f"v1_7_i @ v2_7_i: {v1_7_i @ v2_7_i}")

v1_7_i:
 [4 7 3 8 1 9 8]
v2_7_i:
 [6 2 4 6 8 3 9]
v1_7_i @ v2_7_i: 205


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [6]:
m1_2x2_i = np.random.randint(1, 11, size=(2, 2))
m2_2x3_i = np.random.randint(1, 11, size=(2, 3))
print(f"m1_2x2_i:\n {m1_2x2_i}")
print(f"m2_2x3_i:\n {m2_2x3_i}")
print(f"m1_2x2_i @ m2_2x3_i:\n {m1_2x2_i @ m2_2x3_i}")

m1_2x2_i:
 [[6 5]
 [9 4]]
m2_2x3_i:
 [[1 5 6]
 [4 8 2]]
m1_2x2_i @ m2_2x3_i:
 [[26 70 46]
 [25 77 62]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [7]:
m_3x3_f = np.random.rand(3, 3)
print(f"m_3x3_f:\n {m_3x3_f}")
m_3x3_f_inv = np.linalg.inv(m_3x3_f)
print(f"m_3x3_f_inv:\n {m_3x3_f_inv}")

m_3x3_f:
 [[0.30951476 0.13952285 0.10410801]
 [0.24840572 0.19923609 0.98027332]
 [0.84446419 0.84633716 0.60688404]]
m_3x3_f_inv:
 [[ 5.88027287 -0.02851064 -0.96268027]
 [-5.61745683 -0.82906335  2.30279731]
 [-0.34836539  1.19585173 -0.2240855 ]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [8]:
m_4x4_i = np.random.randint(1, 11, size=(4, 4))
print(f"m_4x4_i:\n {m_4x4_i}")
m_4x4_i_t = m_4x4_i.T
print(f"m_4x4_i_t:\n {m_4x4_i_t}")

m_4x4_i:
 [[10  1  9  3]
 [ 1  5  8  5]
 [ 8  3  5  3]
 [ 1 10  1  4]]
m_4x4_i_t:
 [[10  1  8  1]
 [ 1  5  3 10]
 [ 9  8  5  1]
 [ 3  5  3  4]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [9]:
m_3x4_i = np.random.randint(1, 11, size=(3, 4))
v_4_i = np.random.randint(1, 11, size=4)
print(f"m_3x4_i:\n {m_3x4_i}")
print(f"v_4_i:\n {v_4_i}")
print(f"m_3x4_i @ v_4_i: {m_3x4_i @ v_4_i}")

m_3x4_i:
 [[ 1  8  3  8]
 [ 4 10  6 10]
 [ 9  7  8  6]]
v_4_i:
 [7 1 1 2]
m_3x4_i @ v_4_i: [34 64 90]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [10]:
m_2x3_f = np.random.rand(2, 3)
v_3_f = np.random.rand(3)
print(f"m_2x3_f:\n {m_2x3_f}")
print(f"v_3_f:\n {v_3_f}")
print(f"m_2x3_f @ v_3_f: {m_2x3_f @ v_3_f}")

m_2x3_f:
 [[0.75374565 0.83806704 0.84677209]
 [0.00865843 0.70330262 0.54745726]]
v_3_f:
 [0.00349589 0.33164425 0.58028503]
m_2x3_f @ v_3_f: [0.77194429 0.55095779]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [11]:
m1_2x2_i = np.random.randint(1, 11, size=(2, 2))
m2_2x2_i = np.random.randint(1, 11, size=(2, 2))
print(f"m1_2x2_i:\n {m1_2x2_i}")
print(f"m2_2x2_i:\n {m2_2x2_i}")
print(f"m1_2x2_i * m2_2x2_i:\n {m1_2x2_i * m2_2x2_i}")

m1_2x2_i:
 [[6 2]
 [1 7]]
m2_2x2_i:
 [[ 8 10]
 [ 9  2]]
m1_2x2_i * m2_2x2_i:
 [[48 20]
 [ 9 14]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [12]:
m1_2x2_i = np.random.randint(1, 11, size=(2, 2))
m2_2x2_i = np.random.randint(1, 11, size=(2, 2))
print(f"m1_2x2_i:\n {m1_2x2_i}")
print(f"m2_2x2_i:\n {m2_2x2_i}")
print(f"m1_2x2_i @ m2_2x2_i:\n {m1_2x2_i @ m2_2x2_i}")

m1_2x2_i:
 [[1 8]
 [1 5]]
m2_2x2_i:
 [[2 7]
 [3 5]]
m1_2x2_i @ m2_2x2_i:
 [[26 47]
 [17 32]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [13]:
m_5x5_i = np.random.randint(1, 101, size=(5, 5))
print(f"m_5x5_i:\n {m_5x5_i}")
print(f"Sum of all the elements is {m_5x5_i.sum()}")

m_5x5_i:
 [[52 93  4 26 87]
 [ 2 58 21 44  6]
 [69 55 87  2  9]
 [22 23 20 69 22]
 [14 36 87 66  5]]
Sum of all the elements is 979


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [14]:
m1_4x4_i = np.random.randint(1, 11, size=(4, 4))
m2_4x4_i = np.random.randint(1, 11, size=(4, 4))
print(f"m1_4x4_i:\n {m1_4x4_i}")
print(f"m2_4x4_i:\n {m2_4x4_i}")
print(f"m1_4x4_i - m2_4x4_i):\n {m1_4x4_i - m2_4x4_i}")

m1_4x4_i:
 [[ 7  7  3  2]
 [ 5  4  9  6]
 [ 7  1  9  6]
 [10  2  5  3]]
m2_4x4_i:
 [[ 2  2  3  2]
 [ 3  7  8  7]
 [ 2  1 10  8]
 [ 2  2  5  5]]
m1_4x4_i - m2_4x4_i):
 [[ 5  5  0  0]
 [ 2 -3  1 -1]
 [ 5  0 -1 -2]
 [ 8  0  0 -2]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [15]:
m_3x3_f = np.random.rand(3, 3)
v_3_i = np.full(3, 1)
print(f"m_3x3_f:\n {m_3x3_f}")
print(f"v_3_i:\n {v_3_i}")
print(f"Result:\n {(m_3x3_f @ v_3_i).reshape(-1, 1)}")

m_3x3_f:
 [[0.62064008 0.40762471 0.40357404]
 [0.41697937 0.82299693 0.88011482]
 [0.39340965 0.62378865 0.97142828]]
v_3_i:
 [1 1 1]
Result:
 [[1.43183883]
 [2.12009112]
 [1.98862658]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел. 

In [16]:
m_3x4_i = np.random.randint(1, 11, size=(3, 4))
print(f"m_3x4_i:\n {m_3x4_i}")
print(f"Result:\n {m_3x4_i ** 2}")

m_3x4_i:
 [[5 4 9 6]
 [7 2 4 4]
 [9 5 9 2]]
Result:
 [[25 16 81 36]
 [49  4 16 16]
 [81 25 81  4]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [5]:
v1_4_i = np.random.randint(1, 51, size=4)
print(f"v1_4_i:\n {v1_4_i}")
print(f"Result:\n {(v1_4_i ** 0.5)}")

v1_4_i:
 [49 33 41 47]
Result:
 [7.         5.74456265 6.40312424 6.8556546 ]
